services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile.yunxi
    image: laiber/new-api:yunxi
    container_name: new-api
    restart: unless-stopped
    network_mode: host
    command: --log-dir /app/logs
    env_file:
      - .env.server-yunxi
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=${SQL_DSN}
      - REDIS_CONN_STRING=${REDIS_CONN_STRING}
      - TZ=${TZ:-Asia/Shanghai}
      - BATCH_UPDATE_ENABLED=${BATCH_UPDATE_ENABLED:-true}
      - NODE_NAME=${NODE_NAME:-ai-laiber-cloud}
