services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile.yunxi
    image: laiber/new-api:yunxi
    container_name: new-api
    restart: unless-stopped
    network_mode: host
    command: --log-dir /app/logs
    env_file:
      - .env.server-yunxi
    volumes:
      - ./data:/data
      - ./logs:/app/logs
